# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd21333d875c7579c66fb37a47ad3b6d8a14feb02124806d5695a491a63edf9e23e4da9717d15fa17e0e495bd6c2abcbf346ab7e73863f2b29eeb58a1581ff8f

test:
  secret_key_base: 5c48db24311da226a8f1f8838ac0dfdb11c7d09e9471d443dc011009a8fc9dbb5ef8f3d4209ed36e7f6c1224c1c4e58a92d4308607fd942030f838efad531686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
